# This GitHub Actions workflow is named "Download CRAN Documentation".
# It is triggered by two events:
# 1. A scheduled cron job that runs every Saturday at midnight UTC.
# 2. A push event to the main branch.
#
# The workflow consists of a single job named "download-cran" that runs on the latest Ubuntu environment.
# The job has the following steps:
# 1. Checkout the repository using the actions/checkout@v2 action.
# 2. Set up Python using the actions/setup-python@v2 action, specifying Python version 3.x.
# 3. Install dependencies listed in the requirements.txt file.
# 4. Run a Python script named dlcran.py.
# 5. Compress the `dox` folder into a tar.gz file.
# 6. Configure Git LFS (Large File Storage) to track the compressed file.
# 7. Add and commit the compressed file to the repository using the stefanzweifel/git-auto-commit-action@v5 action.
#    The commit message is "Auto-update CRAN documentation with compressed folder", and the commit is made with
#    the user name "vjvelascorios (GithubActions)" and the email "github-actions@github.com".
name: Download CRAN Documentation

on:
  schedule:
    - cron: '0 0 * * 6'  # Ejecutar cada sábado a medianoche UTC
  push:
    branches:
      - main  # También se ejecuta cuando hay un push a la rama principal

jobs:
  download-cran documentation:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python dlcran.py

    # - name: Compress `dox` folder
    #   run: |
    #     tar -czf dox.tar.gz dox

    # - name: Configure Git LFS
    #   run: |
    #     git lfs install
    #     git lfs track "dox.tar.gz"
    #     git add .gitattributes  # Añade el archivo de configuración de LFS al repositorio

    - name: Add and commit compressed file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update CRAN documentation with compressed folder"
        commit_user_name: "vjvelascorios (GithubActions)"
        commit_author_email: "github-actions@github.com"
        file_pattern: "dox.tar.gz"
