name: Download CRAN Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a medianoche UTC
  push:
    branches:
      - main  # También se ejecuta cuando hay un push a la rama principal

jobs:
  download-cran:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python dlcran.py

    - name: Compress `dox` folder
      run: |
        tar -czf dox.tar.gz dox

    - name: Configure Git LFS
      run: |
        git lfs install
        git lfs track "dox.tar.gz"
        git add .gitattributes  # Añade el archivo de configuración de LFS al repositorio

    - name: Add and commit compressed file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update CRAN documentation with compressed folder"
        commit_user_name: "vjvelascorios (GithubActions)"
        commit_author_email: "github-actions@github.com"
        file_pattern: "dox.tar.gz"
