name: Download CRAN Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a medianoche UTC
  push:
    branches:
      - main  # También se ejecuta cuando hay un push a la rama principal

jobs:
  download-cran:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usa la versión de Python que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install requests beautifulsoup4
        pip install -r requirements.txt

    - name: Run script
      run: python dlcran.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update CRAN documentation"
        commit_user_name: "vjvelascorios (GithubActions)"

   
   
   
        # run: |
      #   git config --global user.name 'github-actions[bot]'
      #   git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #   git add .
      #   git commit -m 'Auto-update CRAN documentation'
      #   git push
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}